import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'

export type InstallOpts = {
  threshold?: number
  model?: string
}

export type PACTState = {
  installed: boolean
  threshold: number
  model: string
  sessionsCompressed: number
  avgRatio: number
  tokensSaved: number
  bytesSaved: number
}

export type SavingsBreakdown = {
  tokensSaved: number
  bytesSaved: number
  usdSaved: number
  pricePerMTokens: number
}

export type StatusResult = PACTState & { savings: SavingsBreakdown }

const DEFAULT_THRESHOLD = 0.60
const DEFAULT_MODEL = 'claude-haiku-4-5-20251001'
// Claude Sonnet 4.6 input pricing — the model most Claude Code sessions use.
// Override with PACT_PRICE_PER_MTOKENS env var for other models.
const DEFAULT_PRICE_PER_MTOKENS = 3.0

function priceUSDPerMTokens(): number {
  const env = process.env.PACT_PRICE_PER_MTOKENS
  if (env) {
    const n = Number(env)
    if (Number.isFinite(n) && n > 0) return n
  }
  return DEFAULT_PRICE_PER_MTOKENS
}

export function computeSavings(state: PACTState): SavingsBreakdown {
  const pricePerMTokens = priceUSDPerMTokens()
  const usdSaved = (state.tokensSaved / 1_000_000) * pricePerMTokens
  return {
    tokensSaved: state.tokensSaved,
    bytesSaved: state.bytesSaved,
    usdSaved,
    pricePerMTokens,
  }
}

function pactDir(projectDir: string) { return join(projectDir, '.pact') }
function stateFile(projectDir: string) { return join(pactDir(projectDir), 'state.json') }
function hookFile(projectDir: string) { return join(pactDir(projectDir), 'hook.js') }
function settingsFile(projectDir: string) { return join(projectDir, '.claude', 'settings.json') }

function emptyState(): PACTState {
  return { installed: false, threshold: DEFAULT_THRESHOLD, model: DEFAULT_MODEL, sessionsCompressed: 0, avgRatio: 0, tokensSaved: 0, bytesSaved: 0 }
}

export function readState(projectDir: string): PACTState {
  const f = stateFile(projectDir)
  if (!existsSync(f)) return emptyState()
  try {
    const parsed = JSON.parse(readFileSync(f, 'utf8')) as Partial<PACTState>
    return { ...emptyState(), ...parsed } as PACTState
  } catch {
    return emptyState()
  }
}

export function writeState(projectDir: string, state: PACTState): void {
  mkdirSync(pactDir(projectDir), { recursive: true })
  writeFileSync(stateFile(projectDir), JSON.stringify(state, null, 2))
}

function generateHookScript(threshold: number, model: string): string {
  return `#!/usr/bin/env node
// .pact/hook.js — auto-generated by pact-cc install. Do not edit.
// Shells out to 'npx pact-cc compress --json' so it works regardless of how
// pact-cc was installed (global, npx, local node_modules).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { spawn } from 'node:child_process'

const THRESHOLD = ${threshold}
const MODEL = '${model}'
const STATE_FILE = '.pact/state.json'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\\n')
}

function loadState() {
  if (existsSync(STATE_FILE)) {
    try { return JSON.parse(readFileSync(STATE_FILE, 'utf8')) } catch { return {} }
  }
  return {}
}

function saveState(state) {
  mkdirSync('.pact', { recursive: true })
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2))
}

function runCompressor(text) {
  return new Promise((resolve) => {
    const child = spawn('npx', ['--yes', 'pact-cc', 'compress', '--json', '--model', MODEL], {
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    let stdout = ''
    child.stdout.on('data', (d) => { stdout += d.toString() })
    child.on('close', () => {
      try { resolve(JSON.parse(stdout.trim())) } catch { resolve(null) }
    })
    child.on('error', () => resolve(null))
    child.stdin.end(text)
  })
}

async function main() {
  let hookInput
  try {
    hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8'))
  } catch {
    respond({ continue: true })
    return
  }

  const contextTokens = hookInput.context_tokens ?? 0
  const maxTokens = hookInput.max_tokens ?? 200000
  const usage = maxTokens > 0 ? contextTokens / maxTokens : 0

  if (usage < THRESHOLD) {
    respond({ continue: true })
    return
  }

  const conversationHistory = hookInput.conversation_history ?? ''
  if (!conversationHistory.trim()) {
    respond({ continue: true })
    return
  }

  const result = await runCompressor(conversationHistory)
  if (!result || !result.ok) {
    respond({ continue: true })
    return
  }

  const state = loadState()
  state.sessionsCompressed = (state.sessionsCompressed ?? 0) + 1
  const n = state.sessionsCompressed
  state.avgRatio = ((state.avgRatio ?? 0) * (n - 1) + result.ratio) / n
  state.tokensSaved = (state.tokensSaved ?? 0) + (result.tokens.before - result.tokens.after)
  const bytesBefore = Buffer.byteLength(conversationHistory, 'utf8')
  const bytesAfter = Buffer.byteLength(result.pact, 'utf8')
  state.bytesSaved = (state.bytesSaved ?? 0) + Math.max(0, bytesBefore - bytesAfter)
  saveState(state)

  respond({
    continue: true,
    prompt_inject: \`[PACT compressed context — ratio: \${result.ratio.toFixed(1)}x]\\n\${result.pact}\`
  })
}

main().catch(() => respond({ continue: true }))
`
}

function mergeHookIntoSettings(settingsPath: string, command = 'node .pact/hook.js', event = 'PreToolUse'): void {
  let settings: Record<string, unknown> = {}
  if (existsSync(settingsPath)) {
    try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')) } catch { /* start fresh */ }
  }

  const hookEntry = {
    type: 'command',
    command
  }

  const hooks = (settings.hooks ?? {}) as Record<string, unknown>
  const eventHooks = (hooks[event] ?? []) as Array<{ matcher: string; hooks: unknown[] }>

  // Check if already installed
  const alreadyInstalled = eventHooks.some(
    (entry) => Array.isArray(entry.hooks) && entry.hooks.some(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, string>).command === command
    )
  )
  if (alreadyInstalled) return

  eventHooks.push({ matcher: '*', hooks: [hookEntry] })
  hooks[event] = eventHooks
  settings.hooks = hooks

  const dir = settingsPath.replace(/\/[^/]+$/, '')
  mkdirSync(dir, { recursive: true })
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n')
}

function removeHookFromSettings(settingsPath: string, command = 'node .pact/hook.js', event = 'PreToolUse'): void {
  if (!existsSync(settingsPath)) return
  let settings: Record<string, unknown>
  try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')) } catch { return }

  const hooks = settings.hooks as Record<string, unknown> | undefined
  if (!hooks) return

  const eventHooks = hooks[event] as Array<{ matcher: string; hooks: unknown[] }> | undefined
  if (!eventHooks) return

  hooks[event] = eventHooks.filter(
    (entry) => !(Array.isArray(entry.hooks) && entry.hooks.some(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, string>).command === command
    ))
  )
  settings.hooks = hooks
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n')
}

function generateStartHookScript(): string {
  return `#!/usr/bin/env node
// .pact/start-hook.js — auto-generated by pact-cc install. Do not edit.
import { readFileSync } from 'node:fs'
import { buildInjection } from '../dist/inject.js'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\\n')
}

async function main() {
  let hookInput
  try { hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8')) } catch {
    respond({ continue: true })
    return
  }
  const usage = (hookInput.context_tokens ?? 0) / (hookInput.max_tokens ?? 200000)
  if (usage >= 0.05) {
    respond({ continue: true })
    return
  }
  respond({ continue: true, prompt_inject: buildInjection() })
}

main().catch(() => respond({ continue: true }))
`
}

function generateStopHookScript(): string {
  return `#!/usr/bin/env node
// .pact/stop-hook.js — auto-generated by pact-cc install. Do not edit.
import { readFileSync } from 'node:fs'
import { extractTags } from '../dist/extract.js'
import { writeSession } from '../dist/session.js'
import { randomBytes } from 'node:crypto'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\\n')
}

async function main() {
  let hookInput
  try { hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8')) } catch {
    respond({ continue: true })
    return
  }
  const transcript = hookInput.conversation_history ?? ''
  const tags = extractTags(transcript)
  if (tags.length > 0) {
    const id = new Date().toISOString().replace(/[:.]/g, '-') + '-' + randomBytes(3).toString('hex')
    writeSession(process.cwd(), id, tags)
  }
  respond({ continue: true })
}

main().catch(() => respond({ continue: true }))
`
}

export async function installPACT(projectDir: string, opts: InstallOpts): Promise<void> {
  const threshold = opts.threshold ?? DEFAULT_THRESHOLD
  const model = opts.model ?? DEFAULT_MODEL

  // Write hook script
  mkdirSync(pactDir(projectDir), { recursive: true })
  writeFileSync(hookFile(projectDir), generateHookScript(threshold, model))
  writeFileSync(join(pactDir(projectDir), 'start-hook.js'), generateStartHookScript())
  writeFileSync(join(pactDir(projectDir), 'stop-hook.js'), generateStopHookScript())

  // Merge into settings.json
  mergeHookIntoSettings(settingsFile(projectDir))
  mergeHookIntoSettings(settingsFile(projectDir), 'node .pact/start-hook.js', 'PreToolUse')
  mergeHookIntoSettings(settingsFile(projectDir), 'node .pact/stop-hook.js', 'Stop')

  // Write state
  writeState(projectDir, {
    installed: true,
    threshold,
    model,
    sessionsCompressed: 0,
    avgRatio: 0,
    tokensSaved: 0,
    bytesSaved: 0,
  })
}

export async function uninstallPACT(projectDir: string): Promise<void> {
  removeHookFromSettings(settingsFile(projectDir))
  removeHookFromSettings(settingsFile(projectDir), 'node .pact/start-hook.js', 'PreToolUse')
  removeHookFromSettings(settingsFile(projectDir), 'node .pact/stop-hook.js', 'Stop')
  const pact = pactDir(projectDir)
  if (existsSync(pact)) {
    rmSync(pact, { recursive: true, force: true })
  }
}

export async function install(projectDir?: string): Promise<void> {
  return installPACT(projectDir ?? process.cwd(), {})
}

export async function uninstall(projectDir?: string): Promise<void> {
  return uninstallPACT(projectDir ?? process.cwd())
}

export async function status(projectDir?: string): Promise<StatusResult> {
  const state = readState(projectDir ?? process.cwd())
  return { ...state, savings: computeSavings(state) }
}
