import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'

export type InstallOpts = {
  threshold?: number
  model?: string
}

export type PACTState = {
  installed: boolean
  threshold: number
  model: string
  sessionsCompressed: number
  avgRatio: number
  tokensSaved: number
}

export type StatusResult = PACTState

const DEFAULT_THRESHOLD = 0.80
const DEFAULT_MODEL = 'claude-haiku-4-5-20251001'

function pactDir(projectDir: string) { return join(projectDir, '.pact') }
function stateFile(projectDir: string) { return join(pactDir(projectDir), 'state.json') }
function hookFile(projectDir: string) { return join(pactDir(projectDir), 'hook.js') }
function settingsFile(projectDir: string) { return join(projectDir, '.claude', 'settings.json') }

export function readState(projectDir: string): PACTState {
  const f = stateFile(projectDir)
  if (!existsSync(f)) {
    return { installed: false, threshold: DEFAULT_THRESHOLD, model: DEFAULT_MODEL, sessionsCompressed: 0, avgRatio: 0, tokensSaved: 0 }
  }
  try {
    return JSON.parse(readFileSync(f, 'utf8')) as PACTState
  } catch {
    return { installed: false, threshold: DEFAULT_THRESHOLD, model: DEFAULT_MODEL, sessionsCompressed: 0, avgRatio: 0, tokensSaved: 0 }
  }
}

export function writeState(projectDir: string, state: PACTState): void {
  mkdirSync(pactDir(projectDir), { recursive: true })
  writeFileSync(stateFile(projectDir), JSON.stringify(state, null, 2))
}

function generateHookScript(threshold: number, model: string): string {
  return `#!/usr/bin/env node
// .pact/hook.js — auto-generated by pact-cc install. Do not edit.
// Shells out to 'npx pact-cc compress --json' so it works regardless of how
// pact-cc was installed (global, npx, local node_modules).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { spawn } from 'node:child_process'

const THRESHOLD = ${threshold}
const MODEL = '${model}'
const STATE_FILE = '.pact/state.json'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\\n')
}

function loadState() {
  if (existsSync(STATE_FILE)) {
    try { return JSON.parse(readFileSync(STATE_FILE, 'utf8')) } catch { return {} }
  }
  return {}
}

function saveState(state) {
  mkdirSync('.pact', { recursive: true })
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2))
}

function runCompressor(text) {
  return new Promise((resolve) => {
    const child = spawn('npx', ['--yes', 'pact-cc', 'compress', '--json', '--model', MODEL], {
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    let stdout = ''
    child.stdout.on('data', (d) => { stdout += d.toString() })
    child.on('close', () => {
      try { resolve(JSON.parse(stdout.trim())) } catch { resolve(null) }
    })
    child.on('error', () => resolve(null))
    child.stdin.end(text)
  })
}

async function main() {
  let hookInput
  try {
    hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8'))
  } catch {
    respond({ continue: true })
    return
  }

  const contextTokens = hookInput.context_tokens ?? 0
  const maxTokens = hookInput.max_tokens ?? 200000
  const usage = maxTokens > 0 ? contextTokens / maxTokens : 0

  if (usage < THRESHOLD) {
    respond({ continue: true })
    return
  }

  const conversationHistory = hookInput.conversation_history ?? ''
  if (!conversationHistory.trim()) {
    respond({ continue: true })
    return
  }

  const result = await runCompressor(conversationHistory)
  if (!result || !result.ok) {
    respond({ continue: true })
    return
  }

  const state = loadState()
  state.sessionsCompressed = (state.sessionsCompressed ?? 0) + 1
  const n = state.sessionsCompressed
  state.avgRatio = ((state.avgRatio ?? 0) * (n - 1) + result.ratio) / n
  state.tokensSaved = (state.tokensSaved ?? 0) + (result.tokens.before - result.tokens.after)
  saveState(state)

  respond({
    continue: true,
    prompt_inject: \`[PACT compressed context — ratio: \${result.ratio.toFixed(1)}x]\\n\${result.pact}\`
  })
}

main().catch(() => respond({ continue: true }))
`
}

function mergeHookIntoSettings(settingsPath: string): void {
  let settings: Record<string, unknown> = {}
  if (existsSync(settingsPath)) {
    try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')) } catch { /* start fresh */ }
  }

  const hookEntry = {
    type: 'command',
    command: 'node .pact/hook.js'
  }

  const hooks = (settings.hooks ?? {}) as Record<string, unknown>
  const preToolUse = (hooks.PreToolUse ?? []) as Array<{ matcher: string; hooks: unknown[] }>

  // Check if already installed
  const alreadyInstalled = preToolUse.some(
    (entry) => Array.isArray(entry.hooks) && entry.hooks.some(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, string>).command === 'node .pact/hook.js'
    )
  )
  if (alreadyInstalled) return

  preToolUse.push({ matcher: '*', hooks: [hookEntry] })
  hooks.PreToolUse = preToolUse
  settings.hooks = hooks

  const dir = settingsPath.replace(/\/[^/]+$/, '')
  mkdirSync(dir, { recursive: true })
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n')
}

function removeHookFromSettings(settingsPath: string): void {
  if (!existsSync(settingsPath)) return
  let settings: Record<string, unknown>
  try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')) } catch { return }

  const hooks = settings.hooks as Record<string, unknown> | undefined
  if (!hooks) return

  const preToolUse = hooks.PreToolUse as Array<{ matcher: string; hooks: unknown[] }> | undefined
  if (!preToolUse) return

  hooks.PreToolUse = preToolUse.filter(
    (entry) => !(Array.isArray(entry.hooks) && entry.hooks.some(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, string>).command === 'node .pact/hook.js'
    ))
  )
  settings.hooks = hooks
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n')
}

export async function installPACT(projectDir: string, opts: InstallOpts): Promise<void> {
  const threshold = opts.threshold ?? DEFAULT_THRESHOLD
  const model = opts.model ?? DEFAULT_MODEL

  // Write hook script
  mkdirSync(pactDir(projectDir), { recursive: true })
  writeFileSync(hookFile(projectDir), generateHookScript(threshold, model))

  // Merge into settings.json
  mergeHookIntoSettings(settingsFile(projectDir))

  // Write state
  writeState(projectDir, {
    installed: true,
    threshold,
    model,
    sessionsCompressed: 0,
    avgRatio: 0,
    tokensSaved: 0,
  })
}

export async function uninstallPACT(projectDir: string): Promise<void> {
  removeHookFromSettings(settingsFile(projectDir))
  const pact = pactDir(projectDir)
  if (existsSync(pact)) {
    rmSync(pact, { recursive: true, force: true })
  }
}

export async function install(projectDir?: string): Promise<void> {
  return installPACT(projectDir ?? process.cwd(), {})
}

export async function uninstall(projectDir?: string): Promise<void> {
  return uninstallPACT(projectDir ?? process.cwd())
}

export async function status(projectDir?: string): Promise<StatusResult> {
  return readState(projectDir ?? process.cwd())
}
