#!/usr/bin/env node
// .pact/hook.js — auto-generated by pact-cc install. Do not edit.
// Shells out to 'npx pact-cc compress --json' so it works regardless of how
// pact-cc was installed (global, npx, local node_modules).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { spawn } from 'node:child_process'

const THRESHOLD = 0.8
const MODEL = 'claude-haiku-4-5-20251001'
const STATE_FILE = '.pact/state.json'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n')
}

function loadState() {
  if (existsSync(STATE_FILE)) {
    try { return JSON.parse(readFileSync(STATE_FILE, 'utf8')) } catch { return {} }
  }
  return {}
}

function saveState(state) {
  mkdirSync('.pact', { recursive: true })
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2))
}

function runCompressor(text) {
  return new Promise((resolve) => {
    const child = spawn('npx', ['--yes', 'pact-cc', 'compress', '--json', '--model', MODEL], {
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    let stdout = ''
    child.stdout.on('data', (d) => { stdout += d.toString() })
    child.on('close', () => {
      try { resolve(JSON.parse(stdout.trim())) } catch { resolve(null) }
    })
    child.on('error', () => resolve(null))
    child.stdin.end(text)
  })
}

async function main() {
  let hookInput
  try {
    hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8'))
  } catch {
    respond({ continue: true })
    return
  }

  const contextTokens = hookInput.context_tokens ?? 0
  const maxTokens = hookInput.max_tokens ?? 200000
  const usage = maxTokens > 0 ? contextTokens / maxTokens : 0

  if (usage < THRESHOLD) {
    respond({ continue: true })
    return
  }

  const conversationHistory = hookInput.conversation_history ?? ''
  if (!conversationHistory.trim()) {
    respond({ continue: true })
    return
  }

  const result = await runCompressor(conversationHistory)
  if (!result || !result.ok) {
    respond({ continue: true })
    return
  }

  const state = loadState()
  state.sessionsCompressed = (state.sessionsCompressed ?? 0) + 1
  const n = state.sessionsCompressed
  state.avgRatio = ((state.avgRatio ?? 0) * (n - 1) + result.ratio) / n
  state.tokensSaved = (state.tokensSaved ?? 0) + (result.tokens.before - result.tokens.after)
  const bytesBefore = Buffer.byteLength(conversationHistory, 'utf8')
  const bytesAfter = Buffer.byteLength(result.pact, 'utf8')
  state.bytesSaved = (state.bytesSaved ?? 0) + Math.max(0, bytesBefore - bytesAfter)
  saveState(state)

  respond({
    continue: true,
    prompt_inject: `[PACT compressed context — ratio: ${result.ratio.toFixed(1)}x]\n${result.pact}`
  })
}

main().catch(() => respond({ continue: true }))
