#!/usr/bin/env node
// .pact/start-hook.js — auto-generated by pact-cc install. Do not edit.
import { readFileSync } from 'node:fs'
import { buildInjection } from '../dist/inject.js'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n')
}

async function main() {
  let hookInput
  try { hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8')) } catch {
    respond({ continue: true })
    return
  }
  const usage = (hookInput.context_tokens ?? 0) / (hookInput.max_tokens ?? 200000)
  if (usage >= 0.05) {
    respond({ continue: true })
    return
  }
  respond({ continue: true, prompt_inject: buildInjection() })
}

main().catch(() => respond({ continue: true }))
