#!/usr/bin/env node
// .pact/stop-hook.js — auto-generated by pact-cc install. Do not edit.
import { readFileSync } from 'node:fs'
import { extractTags } from '../dist/extract.js'
import { writeSession } from '../dist/session.js'
import { randomBytes } from 'node:crypto'

function respond(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n')
}

async function main() {
  let hookInput
  try { hookInput = JSON.parse(readFileSync('/dev/stdin', 'utf8')) } catch {
    respond({ continue: true })
    return
  }
  const transcript = hookInput.conversation_history ?? ''
  const tags = extractTags(transcript)
  if (tags.length > 0) {
    const id = new Date().toISOString().replace(/[:.]/g, '-') + '-' + randomBytes(3).toString('hex')
    writeSession(process.cwd(), id, tags)
  }
  respond({ continue: true })
}

main().catch(() => respond({ continue: true }))
